<?php
/********************************************************************
* @name ProfileEdit
* @abstract - Provides user account editing functionality
* @since Mar 28, 2006
* -------------------------------------------------------------------/
*
* @author		Jameson Lopp jameson@unc.edu
*				Adi Unnithan adi@unc.edu
*				Daniel Watson dcwatson@email.unc.edu
*********************************************************************/

require('config.inc.php');

#-------use the hass password-----------#
$_POST['password'] = md5($_POST['password']);
$_POST['newpassword'] = md5($_POST['newpassword']);
$_POST['newpasswordconfirm'] = md5($_POST['newpasswordconfirm']);
#---------------------------------------#


// if not logged in, redirect to main page
if(!isset($_SESSION['user'])) 
{
	header('Location: index.php');
	return;
}
$user = unserialize($_SESSION['user']);
$smarty->assign_by_ref('user', $user);
	
if (isset ($_POST['update']) && $_POST['update'] == 'Update') {
	// check to make sure user entered the correct current password
	if ( 1 == 1)
	#if ($user->get('password') == $_POST['password'])
	{
		$userToEdit = new UserDAO();
		$userToEdit->set("id", $_POST['id']);
		$userToEdit->set('username', $_POST['username']);
		if ($_POST['newpassword'] != null) // update password if new one was entered
			$userToEdit->set('password', $_POST['newpassword']);
		$userToEdit->set('namefirst', $_POST['namefirst']);
		$userToEdit->set('namelast', $_POST['namelast']);
		$userToEdit->set('email', $_POST['email']);
		$userToEdit->set('organization', $_POST['organization']);
		// user edited successfully, return to user list
		if (! $userToEdit->save()) {
			$smarty->assign('saveError', "An error occurred while updating your profile. Please try again later.");
			exit;
		}
		// check if user has changed email address, if so then send new email confirmation
		if (strcmp($user->get('email'), $_POST['email']) != 0)
		{
			$userToEdit->set('emailConfirmed', 0);
			$userToEdit->save();
			// Send an email with an autogenerated link
			if (strtoupper(substr(PHP_OS,0,3)=='WIN')): $eol="\r\n"; elseif (strtoupper(substr(PHP_OS,0,3)=='MAC')): $eol="\r"; else: $eol="\n"; endif;
	    		$mailsubject = "iFold email confirmation: " . ucwords ($userToEdit->get('namefirst')) . " " . ucwords ($userToEdit->get('namelast'));
	    
	    	# Common Headers
			$headers .= 'From: iFold: Interactive Folding '.$eol;
			$headers .= 'Reply-To: iFold: Interactive Folding'.$eol;
			$headers .= 'Return-Path: iFold: Interactive Folding'.$eol;    // these two to set reply address
			$headers .= "Message-ID: <".$now." TheSystem@".$_SERVER['SERVER_NAME'].">".$eol;
			$headers .= "X-Mailer: PHP v".phpversion().$eol;          // These two to help avoid spam-filters
			# Boundry for marking the split & Multitype Headers
			$mime_boundary=md5(time());
			$headers .= 'MIME-Version: 1.0'.$eol;
			$headers .= "Content-Type: multipart/related; boundary=\"".$mime_boundary."\"".$eol;
			$msg = "";
		
			$link = "http://" . $_SERVER['HTTP_HOST'] . str_replace('profileEdit.php', 'registerConfirm.php', $_SERVER['SCRIPT_NAME']) . "?key=" .
				$_POST['id'] . "|" . sha1(md5($_POST['email']) . md5($_POST['password']) .  md5($_POST['username']));
			# HTML Version
			$msg .= "--".$mime_boundary.$eol;
			$msg .= "Content-Type: text/html; charset=iso-8859-1".$eol;
			$msg .= "Content-Transfer-Encoding: 8bit".$eol;
			$msg .= "<br/>You recently changed your registered email address on iFold.<br/><br/>\n" .
				"\nPlease click on the following link to confirm your new email address:<br/>" .
				"\n\n<a href=\"$link\">$link</a><br/><br/>\n\nThanks!\n\n<br/><br/>iFold Administrators".$eol.$eol;
		
			# Text Version
			$msg .= "--".$mime_boundary.$eol;
			$msg .= "Content-Type: text/plain; charset=iso-8859-1".$eol;
			$msg .= "Content-Transfer-Encoding: 8bit".$eol;
			$msg .= "\nYou recently changed your registered email address on iFold.\n" .
				"\nPlease paste the following link into the location bar of your " .
				"browser and visit it to confirm your new email address:" .
				"\n\n$link\n\nThanks!\n\niFold Administrators".$eol;
			$msg .= "+ + Text Only Email from iFold + +".$eol.$eol;
		
			# Finished
			$msg .= "--".$mime_boundary."--".$eol.$eol;
		
	    		mail ($_POST['email'], $mailsubject, $msg, $headers);
		}
		if (isset($_POST['upgrade']) && $_POST['upgrade'] == 'true') // send email to admin informing them of user's upgrade request
		{
			$props = new IFoldProps();
		   	$smarty->assign_by_ref('userRegConfirm', $userDAO);
		   	$mail_subject = "iFold Registration: " . ucwords ($_POST['namefirst']) . " " . ucwords ($_POST['namelast']) . " has requested an account upgrade.";
    		$mail_message = "{$_POST['namefirst']} {$_POST['namelast']} has just requested an account upgrade for the username: {$_POST['username']}" .
				"\n Their stated reason for the request was: " . stripslashes($_POST['upgradereason']) .
				"\n\nPlease visit the Manage Users page to change their user level:\n" .
				"Thanks, [The iFold Application]";
    		$mail_headers = "From: iFold: Interactive Folding\r\nReply-To:\r\nX-Mailer: iFold Account Upgrade PHP Script" . phpversion ();
    		mail ($props->getAdminEmail(), $mail_subject, $mail_message, $mail_headers);
		}
		// update user vars stored in smarty & session
		$user->set('username', $_POST['username']);
		if ($_POST['newpassword'] != null) // update password if new one was entered
			$user->set('password', $_POST['newpassword']);
		$user->set('namefirst', $_POST['namefirst']);
		$user->set('namelast', $_POST['namelast']);
		$user->set('email', $_POST['email']);
		$user->set('organization', $_POST['organization']);
		$_SESSION['user'] = serialize($user);
		$smarty->assign_by_ref('user', $user);
		$smarty->assign('saveSuccess', "Profile successfully updated");
	}
	else
	{
		$smarty->assign('passwordError', "Invalid current password entered");
	}
}
else if (isset ($_POST['delete']) && $_POST['delete'] == 'Delete Account') {
	$userToDel = new UserDAO();
	$userToDel->set("id", $_POST['id']);
		// user deleted, log user out
	if (! $userToDel->delete()) {
		$smarty->assign('deleteError', "Error in deletion. Please try again later.");
		exit;
	} else {
		header('Location: logout.php');
	}
	exit;
}

$smarty->display_page('profileEdit.tpl');

?>
