-- Preliminary iFold Database File
-- Generated by adi unnithan
-- Includes: users, taskoutputs, taskparams, tasks tables
-- 
-- Host: localhost
-- Generation Time: Feb 28, 2006 at 09:11 PM
-- Server version: 4.1.16
-- PHP Version: 4.3.11
-- 
-- Database: `ifold`
-- 

-- --------------------------------------------------------

-- 
-- Table structure for table `taskoutputs`
-- 

CREATE TABLE `taskoutputs` (
  `id` int(11) NOT NULL auto_increment,
  `task_id` int(11) NOT NULL default '0',
  `pdbZip` varchar(100) NOT NULL default '',
  `gyraVsTime` varchar(100) NOT NULL default '',
  `enerVsTemp` varchar(100) NOT NULL default '',
  `enerVsTime` varchar(100) NOT NULL default '',
  `mpegMovie` varchar(100) NOT NULL default '',
  `heatVsTemp` varchar(100) NOT NULL default '',
  `gyraVsTemp` varchar(100) NOT NULL default '',
  `frequencies` varchar(100) NOT NULL default '',
  `finalFoldStruct` varchar(100) NOT NULL default '',
  `enerVsRuns` varchar(100) NOT NULL default '',
  `RMSD` varchar(100) NOT NULL default '',
  `trajSnapshots` varchar(100) NOT NULL default '',
  `foldProbValue` varchar(100) NOT NULL default '',
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

-- 
-- Table structure for table `taskparams`
-- 

CREATE TABLE `taskparams` (
  `id` int(11) NOT NULL auto_increment,
  `foldtype` varchar(60) NOT NULL default '',
  `pdbFile` varchar(60) NOT NULL default '',
  `trajSnapRange` int(10) NOT NULL default '0',
  `initialTemp` float NOT NULL default '0',
  `finalTemp` float NOT NULL default '0',
  `heatC` float NOT NULL default '0',
  `maxTime` float NOT NULL default '0',
  `structModType` varchar(60) NOT NULL default '',
  `tempRangeScan` double(5,2) NOT NULL default '0.00',
  `numRuns` mediumint(8) NOT NULL default '5',
  `annealingT` float NOT NULL default '0',
  `annealingTh` float NOT NULL default '0',
  `annealingTl` float NOT NULL default '0',
  `alphaRate` float NOT NULL default '0',
  `decoyStructure` varchar(60) NOT NULL default '',
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

-- 
-- Table structure for table `tasks`
-- 

CREATE TABLE `tasks` (
  `id` int(11) NOT NULL auto_increment,
  `param_id` int(11) NOT NULL default '0',
  `name` varchar(60) NOT NULL default '',
  `description` varchar(255) NOT NULL default '',
  `created_on` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `created_by` int(11) NOT NULL default '0',
  `completed_on` timestamp NOT NULL default '0000-00-00 00:00:00',
  `status` varchar(32) NOT NULL default 'queued',
  `queuenum` int(11) NOT NULL default '0',
  `daemon_uri` varchar(100) NOT NULL default '',
  PRIMARY KEY  (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

-- 
-- Table structure for table `users`
-- 

CREATE TABLE `users` (
  `id` int(11) NOT NULL auto_increment,
  `created_on` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `username` varchar(60) NOT NULL default '',
  `password` varchar(60) NOT NULL default '',
  `namefirst` varchar(60) NOT NULL default '',
  `namelast` varchar(60) NOT NULL default '',
  `level` tinyint(4) NOT NULL default '1',
  `email` varchar(100) NOT NULL default '',
  `organization` varchar(100) NOT NULL default '',
  `numtasks` int(10) NOT NULL default '10',
  `cpuHours` int(11) NOT NULL default '100',
  `emailConfirmed` tinyint(1) unsigned NOT NULL default '0',
  `approved` tinyint(1) unsigned NOT NULL default '0',
  PRIMARY KEY  (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=36 ;
