# Autogenerated by java-config
# Command: --set-user-vm=sun-jdk-1.5.0.06
setenv JDK_HOME /opt/sun-jdk-1.5.0.06
setenv JAVAC /opt/sun-jdk-1.5.0.06/bin/javac
setenv PATH /opt/sun-jdk-1.5.0.06/bin:/opt/sun-jdk-1.5.0.06/jre/bin:${PATH}
# VERSION="Sun JDK 1.5.0.06"
setenv MANPATH ${MANPATH}:/opt/sun-jdk-1.5.0.06/man
setenv JAVA_HOME /opt/sun-jdk-1.5.0.06
